name: checkin
on:
  workflow_dispatch:
  schedule:
    - cron: "45 02 * * *"

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: auto checkin for traffic

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: master
    
      - name: checkin
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Run checkin
        env:
          CONFIG_URL: "https://cos.izumichan16.cn/xray/config_cos.json"
        run: python ./.github/actions/checkin/universal.py

      - name: timestamp
        run: date
